[2021-08-29 03:17:25] [info] asio async_connect error: system:111 (Conexão recusada)
[2021-08-29 03:17:25] [info] Error getting remote endpoint: system:107 (Ponto final de transporte não está conectado)
[2021-08-29 03:17:25] [error] handle_connect error: Underlying Transport Error
AlsaOut::AlsaOut() called
PulseOut::PulseOut() called
AlsaOut: destructor
AlsaOut: joining...
AlsaOut: thread finished
AlsaOut: closing device...
AlsaOut: destroyed.
